src/accounts/urls.py
from accounts.views import AccountDeleteView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountRegistrationView, AccountUpdateView, UserRatingView

from debug_toolbar import settings  # noqa

from django.urls import path

app_name = "accounts"

urlpatterns = [
    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('profile/password', AccountPasswordChangeView.as_view(), name='password'),
    path('profile/delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    #
    path('leader_board', UserRatingView.as_view(), name='board')
]

src/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

import debug_toolbar
from django.views.generic import TemplateView

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quiz.urls')),
    # path('core/', include('core.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'core.views.error_400'
handler403 = 'core.views.error_403'
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailsView, TestListView, \
    TestResultQuestionView, TestResultCreateView, TestResultDetailsView, TestResultUpdateView, \
    TestResultDeleteView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),

    path('<uuid:uuid>/', TestDetailsView.as_view(), name='details'),
    path('<uuid:uuid>/results/create', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details', TestResultDetailsView.as_view(),
         name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update', TestResultUpdateView.as_view(),
         name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete', TestResultDeleteView.as_view(),
         name='result_delete'),

    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next', TestResultQuestionView.as_view(),
         name='question'),

]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
              integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
              crossorigin="anonymous">
        <title>QUIZ</title>


        <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
            <div class="container-fluid" style="margin-left: 290px; margin-right: 290px">
                <ul class="navbar-nav">
                    <li>
                        <img src="{% static 'images/tests_logo.png' %}" alt="icon" style="width: 100px; height: 100px;">
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}" style="margin-top: 20px;">🏠</a>
                    </li>
                    <li class="nav-item">
                        <a id="button_1" class="btn btn-outline-secondary" href="{% url 'tests:list' %}">QUIZZES</a>
                    </li>
                    <li class="nav-item">
                        <a id="button_2" class="btn btn-outline-success" href="{% url 'accounts:board' %}">LEADER BOARD</a>
                    </li>
                </ul>


                {% if user.is_authenticated %}

                <div class="navbar-nav">
                {% if user.is_superuser %}
                    <div class="nav-item">
                        <a class="btn btn-info btn-outline-danger" style="color: black; margin-top: 18px; margin-right: 15px;" aria-current="page" href="/admin/">ADMIN</a>
                    </div>
                {% endif %}
                    <div class="nav-item">
                        <a class="btn btn-success btn-outline-primary" style="color: black; margin-top: 10px; margin-right: 15px;" aria-current="page" href="{% url 'accounts:profile' %}">PROFILE<br>&lt;&lt;{{user}}&gt;&gt;</a>
                    </div>
                    <div class="nav-item">
                        <a class="btn btn-primary btn-outline-warning" style="color: black; margin-top: 18px;" aria-current="page" href="{% url 'accounts:logout' %}">LOG OUT</a>
                    </div>
                </div>

            {% else %}

                <ul class="navbar-nav">
                    <li class="nav-item" style="padding-right: 15pt;">
                        <a class="btn btn-primary btn-outline-warning" style="color: black;" aria-current="page" href="{% url 'accounts:login' %}">LOG IN</a>
                    </li>
                    <li>
                        <a class="btn btn-info btn-outline-primary" style="color: black;" aria-current="page" href="{% url 'accounts:registration' %}">SIGN UP</a>
                    </li>
                </ul>
            {% endif %}

            </div>
        </nav>

        <style>

            #button_1, #button_2{
                color: black;
                background-color: white;
                margin-top: 30px;
                margin-left: 10px;
                font-weight: bold;
            }


             body{
                  font-size: 24px;
                  font-family: Serif;
                  color: black;
                  background-color: white;

             }

        </style>

    </head>

    <body>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
                integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
                crossorigin="anonymous"></script>



        <div class="container">
            {% include 'includes/messages.html' %}
            {% block main %}
                {% block action %}{% endblock %}
            {% endblock %}
        </div>


    </body>

</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

    {% block main %}
        {% block action %}TESTS{% endblock %}
        <br><br>
        <div>INDEX PAGE TEXT</div>
    {% endblock %}