src/accounts/urls.py
from accounts.views import AccountDeleteView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountRegistrationView, AccountUpdateView, UserRatingView

from debug_toolbar import settings  # noqa

from django.urls import path

app_name = "accounts"

urlpatterns = [
    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('profile/password', AccountPasswordChangeView.as_view(), name='password'),
    path('profile/delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    #
    path('leader_board', UserRatingView.as_view(), name='board')
]

src/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

import debug_toolbar
from django.views.generic import TemplateView

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quiz.urls')),
    # path('core/', include('core.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'core.views.error_400'
handler403 = 'core.views.error_403'
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

src/accounts/models.py
"""
Module 'models' from the app. "Accounts".
"""

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class User(AbstractUser):

    class Meta:
        permissions = [('view_stats', 'Check statistics')]

    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.SmallIntegerField(default=0)

src/quiz/models.py
"""
The module 'models' from the app. "quiz".
"""
import datetime

from django.db import models
from django.core.validators import MaxValueValidator
from django.utils.functional import cached_property

from accounts.models import User

# Create your models here.
from core.models import BaseModel
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def questions_count(self):
        return self.questions.count()

    @cached_property  # the function is used 3 times in this module
    def defy_user_to_score_to_time(self):
        """
        Defy the user who scored the best result of a test
        in correlation to the time of the completion of the test.

        :return : (dict) a data structure with the sought-for values
                         (best_result, best_user, time_best)

        Local variables:
        results: (QS) instances of the model 'Result'
                      in relation to a specific test
                      as an instance of the class 'Test'
        user_to_score_to_time_list: (list) a list of tuples
                                           containing data on each
                                           result of a completed test
        result: (Result) instance of the model 'Result' in the QS
                         that contains details on results of tests
        scores: (list) scores in tests received by users
                       who have completed them
        user_to_score_to_time: (tuple) information about one result
                                in the list of test results (user_to_score_to_time_list)
                                that includes the user, the score and the time the test was finished
        """
        results = self.results.all()
        user_to_score_to_time_list = []
        for result in results:
            user_to_score_to_time_list.append((result.user, result.num_correct_answers,
                                              (result.write_date - result.create_date)))
        scores = [user_to_score_to_time[1] for user_to_score_to_time in user_to_score_to_time_list]
        best_result = max(scores) if scores else 0  # in case there have been no results yielded yet
        best_user, time_best = None, None     # in case there have been no results yielded yet
        for user_to_score_to_time in user_to_score_to_time_list:
            if user_to_score_to_time[1] == best_result:
                best_user = user_to_score_to_time[0]  # the latter score overrides 'best_user'
                time_best = user_to_score_to_time[2]  # the latter score overrides 'time_best'
        return {'best_result': best_result,
                'best_user': best_user,
                'time_best': (time_best - datetime.timedelta(0, 0, time_best.microseconds)) if time_best else 0
                }

    def get_best_result(self):  # defy_user_to_score_to_time becomes the result of its execution when @cached
        score_user_date = self.defy_user_to_score_to_time
        return f'{score_user_date["best_result"]}/{self.questions_count()}'

    def get_best_user(self):  # defy_user_to_score_to_time becomes the result of its execution when @cached
        score_user_date = self.defy_user_to_score_to_time
        return score_user_date['best_user']

    def get_time_of_best_score(self):  # a function becomes the result of its execution when @cached
        score_user_date = self.defy_user_to_score_to_time
        return score_user_date['time_best']

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    current_order_number = models.PositiveSmallIntegerField(null=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def update_result(self, order_number, question, selected_choices):
        correct_choices = [
            choice.is_correct
            for choice in question.choices.all()
        ]

        correct_answer = True
        for z in zip(selected_choices, correct_choices):
            correct_answer &= (z[0] == z[1])

        # TODO: if BackSpace is clicked in the Browser, 'num_*_answers' is incremented from each 'selected_choices'
        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += (1 - int(correct_answer))
        self.current_order_number = order_number
        if order_number == question.test.questions_count():
            self.state = self.STATE.FINISHED
            user = User.objects.get(id=self.user.id)
            user.rating += self.points()
            user.save()
        self.save()

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def calculate_success_rate(self):  # whithout the 1st 'round' the result may be 1/3 * 100 --> 33.300000000000004
        return f'{round(round(self.num_correct_answers / self.test.questions_count(), ndigits=3) * 100, 1)} %'

    def get_time_of_test(self):
        test_time = self.write_date - self.create_date
        return test_time - datetime.timedelta(0, 0, test_time.microseconds)

src/accounts/forms.py
"""
Module 'forms' for the app 'accounts'.
"""

from django.contrib.auth.forms import PasswordChangeForm, ReadOnlyPasswordHashField, UserChangeForm, UserCreationForm
from django.urls import reverse_lazy

from accounts.models import User


class AccountRegistrationForm(UserCreationForm):
    """
    The class creates an HTML-form to register a new user.
    """

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):
    """
    The class creates an HTML-form to edit information about a user.
    """
    link = reverse_lazy('accounts:password')  # 'profile/password'

    class Meta(UserChangeForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'] = ReadOnlyPasswordHashField(
            label="Password",
            help_text='Raw passwords are not visible. You can change the password using '
                      f'<a href="{self.link}">THIS FORM</a>.')


class AccountPasswordUpdateForm(PasswordChangeForm):
    """
    The class creates an HTML-form to edit information about a user.
    """

src/accounts/views.py
"""
The module contains view-functions for the App. "accounts".
"""
from django.views.generic.list import MultipleObjectMixin

from accounts.forms import AccountPasswordUpdateForm, AccountRegistrationForm, AccountUpdateForm

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import render  # noqa
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView
from django.views.generic.edit import DeleteView

from accounts.models import User

# Create your views here.


class AccountRegistrationView(CreateView):
    """
    The class operates the process of the registration of a new user.
    """
    model = User
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        """
        Modifies the displayed massage that confirms a successful registration.
        """
        result = super().form_valid(form)
        messages.success(self.request, 'A new user has been successfully registered.')
        return result


class AccountLoginView(LoginView):
    """
    The class operates the process of the validation of a user.
    """
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('index')

    def get_redirect_url(self):
        """
        Defines the URL to open after the login.
        """
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        """
        Modifies the displayed massage that confirms a successful login.
        """
        result = super().form_valid(form)
        messages.success(self.request, f'The user <<{self.request.user}>> has logged in successfully.')
        return result


class AccountLogoutView(LogoutView):
    """
    The class operates the process of the validation of a user.
    """
    template_name = 'accounts/logout.html'

    def get_context_data(self, **kwargs):
        messages.success(self.request, 'You have been logged out successfully.')
        return super().get_context_data(**kwargs)


class AccountUpdateView(MultipleObjectMixin, UpdateView):
    """
    The class processes the edit of user's data.
    """
    model = User
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('index')
    form_class = AccountUpdateForm
    paginate_by = 5

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self):
        context = super().get_context_data(object_list=self.get_queryset())
        return context

    def get_queryset(self):
        return self.object.results.all().select_related('user')

    def form_valid(self, form):
        """
        Modifies the displayed massage that confirms a successful profile update.
        """
        result = super().form_valid(form)
        messages.success(self.request, f'The user <<{self.request.user}>> has been successfully updated.')
        return result


class AccountPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """
    Change the account password.
    """
    model = User
    template_name = 'accounts/password.html'
    success_url = reverse_lazy('index')
    form_class = AccountPasswordUpdateForm

    def form_valid(self, form):
        """
        Modifies the displayed massage that confirms a successful password alteration.
        """
        result = super().form_valid(form)
        messages.success(self.request, f'The user <<{self.request.user}>> has successfully changed the password.')
        return result


class AccountDeleteView(LoginRequiredMixin, DeleteView):
    """
    Delete an Account.
    """

    model = User
    success_url = reverse_lazy('index')
    template_name = 'accounts/delete.html'

    def get_context_data(self, **kwargs):
        messages.success(self.request, 'Your account has been successfully deleted.')
        return super().get_context_data(**kwargs)


class UserRatingView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'user/rating.html'
    login_url = reverse_lazy('accounts:login')
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = self.model.objects.all().order_by('-rating', 'username').exclude(rating=0)
        # context['students'] = self.get_filter().qs.select_related('group', 'led_group')  # replaced to get_qs()
        return context

src/accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block main %}
    {% block action %}
        <h2><br>DO YOU CONFIRM THE DELETE OF THE ACCOUNT &lt&lt{{user.username}}&gt&gt?<br><br></h2>
    {% endblock %}
    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}

        <input type="submit" class="btn btn-danger" value="DELETE">
        <a href="{% url 'accounts:profile' %}" class="btn btn-info">UNDO DELETE</a>
    </form>
    <br>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {% block main %}
        {% block action %}
            <h2><br>LOGIN<br><br></h2>
        {% endblock %}
        <form method='post'>
            {% csrf_token %}
            {{form|crispy}}<br>
            <input type="submit" class="btn btn-success" value="LOGIN">

        </form>
    {% endblock %}

src/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    {% block action %}
        <h2><br>LOG IN or RETURN TO THE MAIN PAGE</h2>
        <br>
    {% endblock %}

    <a class="btn btn-info btn-outline-primary" style="color: white;" href="{% url 'index' %}">HOME PAGE</a>
    <a class="btn btn-primary btn-outline-warning" href="{% url 'accounts:login' %}">LOG IN</a>
{% endblock %}

src/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    {% block action %}
        <h2><br>CHANGE YOUR CURRENT PASSWORD<br><br></h2>
    {% endblock %}
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <input type="submit" class="btn btn-success" value="SAVE" style="margin-right: 30pt;">
        <a href="{% url 'accounts:profile' %}" class="btn btn-info">Return</a>
    </form>
    <br>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



    {% block main %}
        {% block action %}
            <h2><br>YOUR CURRENT PROFILE<br><br></h2>
        {% endblock %}
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}

            <div class="media">
<!--                <div class="img-circle.vert">-->
<!--                    <img class="rounded-circle p-1 m-1" width="200" height="200" alt="default" src="{{ user.profile.image.url }}">-->
<!--                </div>-->
                <div class="media-body  p-3 m-3">
                    <h2 class="account-heading" style="margin-top: 15px;">USERNAME: &lt&lt{{ user.username }}&gt&gt</h2>
                    <h3 class="account-heading">FULL NAME: {{ user.first_name }} {{ user.last_name }}</h3>
                    <p class="text-secondary">EMAIL: {{ user.email }}</p>
                </div>
            </div>

            <br>
            {{form|crispy}}

             {% if object_list %}
                <br>
                <div style="text-align:center;">TEST RESULTS:</div>
                <br>
                <table class="table table-striped table-hover" style="text-align:center;">
                      <tr>
                        <th>#</th>
                        <th>Test name</th>
                        <th>Create date</th>
                        <th>Write date</th>
                        <th>Points</th>
                        <th>State</th>
                      </tr>
                            {% for result in object_list %}
                                  <tr>
                                    <td>{{ page_obj.start_index|add:forloop.counter0}}</td>
                                    <td>{{ result.test }}</td>
                                    <td>{{ result.format_create_date }}</td>
                                    <td>{{ result.format_write_date }}</td>
                                    <td>{{ result.points }}</td>
                                    <td>{{ result.get_state_display }}</td>
                                  </tr>
                            {% endfor %}
                </table>
            <div style="margin-left: 20px;">TOTAL SCORE: {{ user.rating }}</div>
            <br>
            {% endif %}

            <div class="p-1 m-1">{% include 'includes/pagination.html' %}</div>
            <br>
            <input type="submit" class="btn btn-success" value="SAVE">
            <a href="{% url 'accounts:delete' user.id %}" class="btn btn-danger">DELETE THIS ACCOUNT</a>
        </form>
        <br>
    {% endblock %}

src/accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    {% block action %}
        <h2><br>REGISTRATION<br><br></h2>
    {% endblock %}
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}<br>
        <input type="submit" class="btn btn-success" value="Create">
    </form>
    <br>
{% endblock %}